### ISSUE TITLE
about the performance number

### ISSUE THREAD

**Issue by wangliwei-intel** [nbdd0121/r2vm#3]
Hi,
I'm reading your paper, very impressive.
I have a question about the performance number.
Let's say we're simulating 4 cores platform with performance 25MIPS.
Is this number for a single core or the sum of 4 cores?

Thanks.
B. R.
Liwei

**Comment by nbdd0121** [comment]
The performance number quoted are all measured as MInst per CPU second. So for behavioural simulation (multi-threaded), the number would be per-core (or per-hart) number, and for cycle-level simulation, because all harts runs in a single thread, the number would be per 4 cores.

**Comment by wangliwei-intel** [comment]
understood, thank you.

B. R.
Liwei
